name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker Login
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        echo "Init login"
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_ACCESS_TOKEN
        echo "Finish Login"
    
    - name: Build Docker Image
      run: |
        docker build -t tomasdelizia/docker-graphql-actions:0.0.1 .
        docker build -t tomasdelizia/docker-graphql-actions:latest .

    - name: Push Docker Image
      run: |
        docker push tomasdelizia/docker-graphql-actions:0.0.1
        docker push tomasdelizia/docker-graphql-actions:latest
